/**
 * Application entry point — mounts <App /> inside a BrowserRouter.
 *
 * `basename` is auto-derived from Vite's BASE_URL so the same build works
 * both at the site root in dev (`/`) and under the GH-Pages subpath in
 * production (`/raazkhnl_hub/`). A `dist/404.html` copy of `index.html` is
 * generated by the postbuild step so deep links don't 404 on GH-Pages.
 */
import React from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import App from './App';
import './src/index.css';

const rootElement = document.getElementById('root');
if (!rootElement) throw new Error('Could not find root element to mount to');

const basename = (import.meta.env.BASE_URL || '/').replace(/\/$/, '') || '/';

ReactDOM.createRoot(rootElement).render(
  <React.StrictMode>
    <BrowserRouter basename={basename}>
      <App />
    </BrowserRouter>
  </React.StrictMode>
);
